### ISSUE TITLE
No exported member

### ISSUE THREAD

**Issue by bjornharvold** [rodolfocop/ng2-datepicker-bootstrap#1]
Hi,

Getting this when trying to import:
 Module '"/Users/crash/git/test/node_modules/ng2-datepicker-bootstrap/index"' has no exported member 'DatePickerModule'.)

Using Angular 2.4.2.

Cheers

**Comment by rodolfocop** [comment]
Hi sorry for the delay, i really was wrong with the module. 
I made the changes, any questions open issue.
If I have solved the problem I will close this

**Comment by bjornharvold** [comment]
Thanks for the fast response!

I don't think the release has made its way to the npm repo yet. Cannot find it.

**Comment by rodolfocop** [comment]
Hi, sorry but I ended up not updating on npm. 
You can use it now!
Thanks!

**Comment by bjornharvold** [comment]
Next error:

ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /Users/crash/git/foo/foo-spa-frontend/node_modules/ng2-datepicker-bootstrap/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in /Users/crash/git/foo/foo-spa-frontend/node_modules/ng2-datepicker-bootstrap/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in /Users/crash/git/foo/foo-spa-frontend/node_modules/ng2-datepicker-bootstrap/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in /Users/crash/git/foo/foo-spa-frontend/node_modules/ng2-datepicker-bootstrap/node_modules/@angular/core/index.d.ts, resolving symbol DatePickerModule in /Users/crash/git/foo/foo-spa-frontend/node_modules/ng2-datepicker-bootstrap/src/datepicker/datepicker.module.ts, resolving symbol DatePickerModule in /Users/crash/git/foo/foo-spa-frontend/node_modules/ng2-datepicker-bootstrap/src/datepicker/datepicker.module.ts

ERROR in ./~/ng2-datepicker-bootstrap/src/datepicker/datepicker.component.ts
Module not found: Error: Can't resolve 'datepicker.component.html' in '/Users/crash/git/foo/foo-spa-frontend/node_modules/ng2-datepicker-bootstrap/src/datepicker'
 @ ./~/ng2-datepicker-bootstrap/src/datepicker/datepicker.component.ts 289:22-58
 @ ./~/ng2-datepicker-bootstrap/src/datepicker/index.ts
 @ ./~/ng2-datepicker-bootstrap/index.ts

Also, does your date picker support reactive forms?

**Comment by rodolfocop** [comment]
Hi, I had not tested with react forms yet. 
I will check and inform you as soon as possible.

**Comment by rodolfocop** [comment]
Hi @bjornharvold, sorry for the delay, I ran some tests using reactive forms and got no problems. 
This error is somewhat tied to AOT. I will try to update this week's component so that it can be used using AOT.

**Comment by rodolfocop** [comment]
Hi, I made an update for a version angular 4 using CLI 1.0 and AOT.

Any questions open issues
