### ISSUE TITLE
Do not provide source code in npm

### ISSUE THREAD

**Issue by jlberrocal** [rodolfocop/ng2-datepicker-bootstrap#2]
First all thanks because what you are providing is a very necessary component in modern apps, but you must be careful with somethings:

1) Are you sure that your component is AoT ready? i mean, you are providing the entire source code, not a bundled version i suggest you to use rollupJS is very easy to configure you can take a look of this [configuration](https://github.com/jlberrocal/ng2-dynatable/blob/master/rollup.config.js) if you want.
2) Never mind publish the node_modules as part of your library, because it will increase significantly the library weight

Once again thanks for the component, if you want i can help you with your component.

**Comment by rodolfocop** [comment]
Hi, thanks for this. I'm trying to sort things out here. As soon as I finish I will update them.
